# Generated by Django 3.1.6 on 2021-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='dataa',
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='upload',
            field=models.FileField(default=False, upload_to='media'),
        ),
    ]
