# Generated by Django 3.1.6 on 2021-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210220_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
