# Generated by Django 3.1.6 on 2021-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210221_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
        migrations.RemoveField(
            model_name='data',
            name='upload',
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
