# Generated by Django 3.1.6 on 2021-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210222_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
