# Generated by Django 3.1.6 on 2021-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210222_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_resets',
            fields=[
                ('id', models.AutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=100)),
                ('is_used', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
