# Generated by Django 3.1.6 on 2021-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_password_resets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_resets',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
